// <auto-generated />
using System;
using DukkanDepo.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DukkanDepo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622164016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DukkanDepo.Domain.Entities.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<int?>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cins")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Iskonto")
                        .HasColumnType("REAL");

                    b.Property<double?>("IskontoluTutar")
                        .HasColumnType("REAL");

                    b.Property<string>("Kod")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Satis")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Tutar")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DukkanDepo.Domain.Entities.KislikUrun", b =>
                {
                    b.HasBaseType("DukkanDepo.Domain.Entities.Urun");

                    b.ToTable("KislikUrunler", (string)null);
                });

            modelBuilder.Entity("DukkanDepo.Domain.Entities.YazlikUrun", b =>
                {
                    b.HasBaseType("DukkanDepo.Domain.Entities.Urun");

                    b.ToTable("YazlikUrunler", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
